
import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "Crystal Falls Couture Gown",
    slug: "crystal-falls-gown",
    description: "Váy couture sequin tím lavender — ánh sáng tinh thể như thác pha lê, dành cho sự kiện cao cấp.",
    shortDescription: "Váy dạ hội màu đen",
    sku: "CFGC-001",
    price: 79900000,
    discountPrice: null,
    stockQuantity: 10,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "clothing",
    image: "/images/crystal-falls-gown.png",
    images: [
      "/images/crystal-falls-gown.png",
      "/images/midnight-sovereign-gown.png",
      "/images/winter1.png",
    ],
    details: [
      "Form dáng couture ôm thân, tôn đường eo và vai.",
      "Hoàn thiện thủ công với hiệu ứng sequin bắt sáng.",
      "Phù hợp tiệc tối, dạ hội và sự kiện trang trọng.",
    ],
    collection: "Couture 2026",
    material: "Lưới cao cấp, sequin ánh tím, lớp lót satin mềm.",
    care: "Giặt khô chuyên nghiệp, treo bằng móc đệm vai.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: 2,
    name: "Winter Aurora",
    slug: "winter-aurora",
    description: "Váy dạ haute couture phối lông thú tinh tế — biểu tượng của sự sang trọng mùa đông.",
    shortDescription: "Váy mùa đông",
    sku: "WA-001",
    price: 24900000,
    discountPrice: null,
    stockQuantity: 15,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "clothing",
    image: "/images/winter1.png",
    images: [
      "/images/winter1.png",
      "/images/crystal-falls-gown.png",
      "/images/Spring1.png",
    ],
    details: [
      "Phom áo khoác váy mùa đông với phần cổ nổi bật.",
      "Tạo cảm giác sang trọng nhưng vẫn giữ độ mềm mại.",
      "Dễ phối cùng găng tay, clutch và trang sức ánh bạc.",
    ],
    collection: "Winter Aurora",
    material: "Dạ cao cấp, lông trang trí, lót satin.",
    care: "Giặt khô, tránh ép nhiệt trực tiếp vào phần lông.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: 3,
    name: "Spring Blossom",
    slug: "spring-blossom",
    description: "Váy vàng tầng lớp — tinh khôi như cánh hoa đầu mùa.",
    shortDescription: "Váy mùa xuân",
    sku: "SB-001",
    price: 19900000,
    discountPrice: null,
    stockQuantity: 20,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "clothing",
    image: "/images/Spring1.png",
    images: [
      "/images/Spring1.png",
      "/images/winter1.png",
      "/images/midnight-sovereign-gown.png",
    ],
    details: [
      "Thiết kế tầng lớp tạo chuyển động nhẹ khi di chuyển.",
      "Màu vàng mềm giúp tổng thể tươi sáng và nữ tính.",
      "Phù hợp tiệc ban ngày, resort và sự kiện ngoài trời.",
    ],
    collection: "Spring Blossom",
    material: "Organza, voan tầng, lớp lót satin.",
    care: "Giặt khô hoặc hấp hơi nhẹ, tránh gấp nếp lâu.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: 4,
    name: "Midnight Sovereign Gown",
    slug: "midnight-sovereign-gown",
    description: "Váy đen mermaid satin — thanh lịch, quyền uy, dành cho buổi tối cao cấp.",
    shortDescription: "Váy đen",
    sku: "MSG-001",
    price: 12900000,
    discountPrice: null,
    stockQuantity: 25,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "clothing",
    image: "/images/midnight-sovereign-gown.png",
    images: [
      "/images/midnight-sovereign-gown.png",
      "/images/crystal-falls-gown.png",
      "/images/Spring1.png",
    ],
    details: [
      "Dáng mermaid kéo dài tỉ lệ cơ thể.",
      "Bề mặt satin đen tạo hiệu ứng tối giản và quyền lực.",
      "Lý tưởng cho gala, tiệc tối và sự kiện black-tie.",
    ],
    collection: "Midnight Edit",
    material: "Satin cao cấp, dựng corset nhẹ, khóa ẩn sau lưng.",
    care: "Giặt khô, bảo quản trong túi áo chuyên dụng.",
    sizes: ["XS", "S", "M", "L"],
  },
  // Trang sức
  {
    id: 5,
    name: "Pearl Grace - Vòng cổ ngọc trai",
    slug: "pearl-grace-necklace",
    description: "Vòng cổ ngọc trai nước ngọt trắng tinh khiết, kết hợp vàng hồng 14K.",
    shortDescription: "Vòng cổ ngọc trai",
    sku: "PGN-001",
    price: 8900000,
    discountPrice: 7900000,
    stockQuantity: 12,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "jewelry",
    image: "/images/Banner_Pearl.png",
    images: [
      "/images/Banner_Pearl.png",
    ],
    details: [
      "Ngọc trai nước ngọt 8-9mm, hình cầu hoàn hảo.",
      "Vòng kim loại mạ vàng hồng 14K không gây dị ứng.",
      "Độ dài có thể điều chỉnh 40-45cm.",
    ],
    collection: "Pearl Grace",
    material: "Ngọc trai nước ngọt, hợp kim mạ vàng hồng 14K.",
    care: "Tránh tiếp xúc nước và hóa chất, lau bằng vải mềm sau mỗi lần sử dụng.",
    sizes: ["One Size"],
  },
  {
    id: 6,
    name: "Pearl Grace - Nhẫn ngọc trai",
    slug: "pearl-grace-ring",
    description: "Nhẫn ngọc trai đơn giản nhưng tinh tế, dành cho những người yêu thích sự tối giản.",
    shortDescription: "Nhẫn ngọc trai",
    sku: "PGR-001",
    price: 4500000,
    discountPrice: null,
    stockQuantity: 20,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "jewelry",
    image: "/images/Banner_Pearl.png",
    images: [
      "/images/Banner_Pearl.png",
    ],
    details: [
      "Ngọc trai 7-8mm.",
      "Vòng kim loại mạ vàng 14K.",
      "Kích thước có sẵn: 52, 54, 56, 58.",
    ],
    collection: "Pearl Grace",
    material: "Ngọc trai nước ngọt, hợp kim mạ vàng 14K.",
    care: "Tránh nước và hóa chất, bảo quản trong hộp riêng.",
    sizes: ["52", "54", "56", "58"],
  },
  {
    id: 7,
    name: "Pearl Grace - Khuyên tai ngọc trai",
    slug: "pearl-grace-earrings",
    description: "Khuyên tai ngọc trai dropping, nhẹ nhàng và sang trọng.",
    shortDescription: "Khuyên tai ngọc trai",
    sku: "PGE-001",
    price: 5200000,
    discountPrice: null,
    stockQuantity: 15,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "jewelry",
    image: "/images/Banner_Pearl.png",
    images: [
      "/images/Banner_Pearl.png",
    ],
    details: [
      "Ngọc trai 6-7mm.",
      "Chốt silver 925 không gây dị ứng.",
      "Thiết kế dropping, phù hợp mọi khuôn mặt.",
    ],
    collection: "Pearl Grace",
    material: "Ngọc trai nước ngọt, bạc 925.",
    care: "Tránh tiếp xúc nước mặn và hóa chất tẩy rửa.",
    sizes: ["One Size"],
  },
  {
    id: 8,
    name: "Auric - Vòng tay vàng tối giản",
    slug: "auric-minimal-bracelet",
    description: "Vòng tay vàng 18K mảnh, thiết kế tối giản, dễ phối cùng mọi trang phục.",
    shortDescription: "Vòng tay vàng",
    sku: "AMB-001",
    price: 15900000,
    discountPrice: null,
    stockQuantity: 8,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "jewelry",
    image: "/images/auric-minimal-ring.png",
    images: [
      "/images/auric-minimal-ring.png",
    ],
    details: [
      "Vàng 18K, trọng lượng ~2.5g.",
      "Độ dài 16cm + 2cm mở rộng.",
      "Khóa dễ dùng, chắc chắn.",
    ],
    collection: "Auric",
    material: "Vàng 18K.",
    care: "Đánh bóng định kỳ bằng vải chuyên dụng.",
    sizes: ["One Size"],
  },
  // Phụ kiện
  {
    id: 9,
    name: "Túi xách da yên tinh khôi",
    slug: "leather-clutch-bag",
    description: "Túi clutch da thật màu be, kích thước vừa vặn, phù hợp tiệc tối.",
    shortDescription: "Túi clutch da",
    sku: "LCB-001",
    price: 6900000,
    discountPrice: 5900000,
    stockQuantity: 18,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "accessories",
    image: "/images/tui-xach-da-yen.png",
    images: [
      "/images/tui-xach-da-yen.png",
    ],
    details: [
      "Da thật mềm mịn.",
      "Kích thước 24 x 15 x 6 cm.",
      "Khoang đựng vừa điện thoại, son môi và thẻ tín dụng.",
    ],
    collection: "Essentials",
    material: "Da bò thật.",
    care: "Bảo quản nơi khô ráo, dùng dầu dưỡng da định kỳ.",
    sizes: ["One Size"],
  },
  {
    id: 10,
    name: "Gót sen na ha thủy tinh",
    slug: "glass-slipper-heels",
    description: "Giày gót cao trong suốt như thủy tinh, làm nổi bật đôi chân bạn.",
    shortDescription: "Giày gót thủy tinh",
    sku: "GSH-001",
    price: 8900000,
    discountPrice: null,
    stockQuantity: 10,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "accessories",
    image: "/images/got-sen-na-ha-thuy-tinh.png",
    images: [
      "/images/got-sen-na-ha-thuy-tinh.png",
    ],
    details: [
      "Gót 10cm, có phần đệm êm.",
      "Chất liệu nhựa cao cấp trong suốt.",
      "Đế giày chống trượt.",
    ],
    collection: "Evening",
    material: "Nhựa cao cấp, da lót chân.",
    care: "Tránh va đập mạnh, lau bằng vải ướt nhẹ.",
    sizes: ["36", "37", "38", "39", "40"],
  },
  {
    id: 11,
    name: "Thắt lưng hao quang",
    slug: "rhinestone-belt",
    description: "Thắt lưng được đính full đá, tạo điểm nhấn cho mọi trang phục đơn giản.",
    shortDescription: "Thắt lưng đính đá",
    sku: "RHB-001",
    price: 3500000,
    discountPrice: 2900000,
    stockQuantity: 22,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "accessories",
    image: "/images/that-lung-hao-quang.png",
    images: [
      "/images/that-lung-hao-quang.png",
    ],
    details: [
      "Đá rhinestone sáng bóng.",
      "Độ dài có thể điều chỉnh.",
      "Khóa vàng sang trọng.",
    ],
    collection: "Evening",
    material: "Vải thun, đá rhinestone, hợp kim.",
    care: "Không giặt máy, giặt tay nhẹ.",
    sizes: ["One Size"],
  },
  {
    id: 12,
    name: "Mũ cải thiên thần nhỏ",
    slug: "mini-top-hat",
    description: "Mũ top hat mini đính lông vũ, hoàn thiện phong cách vintage.",
    shortDescription: "Mũ top hat mini",
    sku: "MTH-001",
    price: 2800000,
    discountPrice: null,
    stockQuantity: 14,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "accessories",
    image: "/images/mu-cai-thien-than-nho.png",
    images: [
      "/images/mu-cai-thien-than-nho.png",
    ],
    details: [
      "Kích thước mini 15cm.",
      "Gắn kẹp tóc chắc chắn.",
      "Đính lông vũ mềm mại.",
    ],
    collection: "Vintage",
    material: "Vải nỉ, lông vũ, kẹp tóc.",
    care: "Bảo quản nơi khô ráo, tránh bẹt mũ.",
    sizes: ["One Size"],
  },
];

export function formatPrice(vnd: number) {
  return new Intl.NumberFormat("vi-VN").format(vnd) + " VNĐ";
}

export function getProduct(id: string | number) {
  return products.find((p) => p.id === Number(id));
}

export function getByCategory(category?: string) {
  if (!category || category === "all") return products;
  return products.filter((p) => p.category === category);
}

